=== djni-r/epam-pr5-xml-parsing/files/papers/papers.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="https://www.github.com/makar-y/epam-pr5-xml-parsing.git/files/papers"
	xmlns:c="https://www.github.com/makar-y/epam-pr5-xml-parsing.git/files/papers">
  <simpleType name="Index">
    <restriction base="ID">
      <pattern value="(\\d){5}"/>
    </restriction>
  </simpleType>
  
  <complexType name="PeriodicalType">

    <attribute name="index" type="tns:Index" use="required"/>

    <attribute name="period" use="optional">
      <simpleType>
	<restriction base="string">
	  <enumeration value="daily"/>
	  <enumeration value="weekly"/>
	  <enumeration value="monthly"/>
	</restriction>
      </simpleType>
    </attribute>
	    
    <sequence>
      <element name="title" type="string"/>
      <element name="volume" type="integer"/>
    </sequence>
  </complexType>

  <complexType name="Newspaper">
    <complexContent>
      <extension base="tns:PeriodicalType">
	<element name="colored" type="boolean"/>
      </extension>
    </complexContent>
  </complexType>

  <complexType name="Magazine">
    <complexContent>
      <extension base="tns:PeriodicalType">
	<element name="metallic" type="boolean"/>
      </extension>
    </complexContent>
  </complexType>
  
  <element name="periodical" type="tns:PeriodicalType" abstract="true"/>
  <element name="newspaper" type="tns:Newspaper" substitutionGroup="tns:periodical"/>
  <element name="magazine" type="tns:Magazine" substitutionGroup="tns:periodical"/>

  <element name="papers">
    <complexType>
      <sequence>
	<element ref="tns:periodical" maxOccurs="unbounded"/>
      </sequence>
    </complexType>
  </element>
  
</schema>

=== djni-r/epam-pr5-xml-parsing/files/papers/papers.xml
<?xml version="1.0" encoding="UTF-8"?>
<papers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:c="https://www.github.com/makar-y/epam-pr5-xml-parsing.git/files/papers"
	xsi:schemaLocation="https://www.github.com/makar-y/epam-pr5-xml-parsing.git/files/papers papers.xsd">

  <newspaper index="34523" period="daily">
    <title>New York Times</title>
    <volume>48</volume>
    <colored>true</colored>
  </newspaper>
  <newspaper index="45234" period="daily">
    <title>Sun Times</title>
    <volume>16</volume>
    <colored>true</colored>
  </newspaper>
  <newspaper index="33423" period="weekly">
    <title>Harvard gazette</title>
    <volume>12</volume>
    <colored>false</colored>
  </newspaper>
  <newspaper index="23523" period="weekly">
    <title>Baltimore Times</title>
    <volume>48</volume>
    <colored>true</colored>
  </newspaper>
  <newspaper index="32343" period="weekly">
    <title>The Daily Mash</title>
    <volume>36</volume>
    <colored>true</colored>
  </newspaper>
  <newspaper index="12323" period="weekly">
    <title>Kentucky Tribune</title>
    <volume>48</volume>
    <colored>true</colored>
  </newspaper>
  <newspaper index="23423" period="monthly">
    <title>Texas View</title>
    <volume>48</volume>
    <colored>false</colored>
  </newspaper>
  <newspaper index="63546" period="daily">
    <title>Denver Daily</title>
    <volume>12</volume>
    <colored>false</colored>
  </newspaper>
  <!--
  <magazine index="54363">
    <title>Cosmopolitan</title>
    <volume>94</volume>
    <metallic>true</metallic>
  </magazine>
  <magazine index="23453">
    <title>Hollywood Reporter</title>
    <volume>86</volume>
    <metallic>true</metallic>
  </magazine>
  <magazine index="67453" period="quarterly">
    <title>US Literary</title>
    <volume>128</volume>
    <metallic>false</metallic>
  </magazine>
  <magazine index="08543">
    <title>Art in America</title>
    <volume>94</volume>
    <metallic>true</metallic>
  </magazine>
  <magazine index="23442" period="monthly">
    <title>National Geographic</title>
    <volume>140</volume>
    <metallic>true</metallic>
  </magazine>
  <magazine index="28453">
    <title>US History Magazine</title>
    <volume>92</volume>
    <metallic>false</metallic>
  </magazine>
  <magazine index="98453" period="weekly">
    <title>Cars</title>
    <volume>64</volume>
    <metallic>true</metallic>
  </magazine>
  <magazine index="23753" period="monthly">
    <title>Men's Health</title>
    <volume>94</volume>
    <metallic>true</metallic>
    </magazine>
  -->
</papers>
